version: '3.9'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: yotemi_front
    restart: always
    tty: true
    env_file:
      - .env
    networks:
      - yotemi

networks:
  yotemi:
    external: true